//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToTallman.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ToTallman.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nicotine
        ///micafungin
        ///calcium + colecalciferol + magnesium + zinc + copper + manganese
        ///triglycerides medium chain formula
        ///nizatidine
        ///disopyramide
        ///insulin isophane human
        ///soy protein and fat formula with vitamins and minerals carbohydrate free
        ///whey protein formula supplemented with amino acids, long chain polyunsaturated fatty acids, vitamins and minerals, low in protein, phosphate, potassium and lactose
        ///teicoplanin
        ///glucose
        ///paper wasp venom
        ///miconazole + zinc oxide
        ///anecortave
        ///clostridium botulinum type A toxin-h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MedicinalProductTerms {
            get {
                return ResourceManager.GetString("MedicinalProductTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to actoNEL
        ///actoS
        ///aKAMin
        ///aCLin
        ///alDOMET
        ///alDACTONE
        ///alODORM
        ///amARYl
        ///amOXil
        ///amiODAROne
        ///amLODIPine
        ///amiTRIPTYLine
        ///amiNOPHYLLine
        ///aPomine
        ///aVomine
        ///arATAC
        ///arOPAX
        ///arABLOC
        ///ARIPiprazole
        ///RABEprazole
        ///aTRopt
        ///aZopt
        ///azATHIOPRINE
        ///aziTHROMYCIN
        ///ERYthromycin
        ///bisOPROLOl
        ///bisACODYl
        ///buMETANide
        ///buDESONide
        ///caRAFate
        ///caLTRate
        ///CARBAMazepine
        ///OXCARBazepine
        ///carbiMAZOLe
        ///caRVEDILOl
        ///caPTOPRil
        ///celAPRAM
        ///celEBREX
        ///ciprAMIL
        ///ciprOXIN
        ///cLARITHROMYcin
        ///ciPROFLOXAcin
        ///cLOMIPRAMine
        ///cLOMIPHEne
        ///cHLORPROMAZine
        ///coUMADIN        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Tallmen {
            get {
                return ResourceManager.GetString("Tallmen", resourceCulture);
            }
        }
    }
}
