#!/usr/bin/env node
//
// compile-lists.js
//
// Shared, language-agnostic compiler for the canonical Tall Man lists.
//
// This is the SINGLE place where list semantics happen: NFC normalization,
// casefold match-key derivation, and the per-list multi-word lookahead cap.
// It emits one versioned artifact (tallman-lists/compiled/lists.compiled.json)
// that every language's (thin) code generator consumes, so all embeddings stay
// byte-identical. Per-language scripts must NOT re-derive any of this.

const fs = require('fs');
const path = require('path');

const rootDir = path.join(__dirname, '..', '..');
const listsDir = path.join(rootDir, 'tallman-lists');
const outDir = path.join(listsDir, 'compiled');
const outFile = path.join(outDir, 'lists.compiled.json');

// Canonical match key = casefold(NFC(text)).
//
// "casefold" is Unicode default (full) case folding. All current entries are
// ASCII/Latin, for which toLowerCase() is exactly equal to that folding. If
// non-ASCII entries are ever added, replace this single function with a real
// Unicode case-folding implementation (and align every language runtime's fold
// to match), per spec section 3.2.
function casefoldKey(text) {
  return text.normalize('NFC').toLowerCase();
}

// A "word" is a run of Unicode letters/combining marks. The runtime multi-word
// lookahead never needs to scan more words than the longest entry contains, so
// we embed this cap per list.
function wordCount(text) {
  const matches = text.normalize('NFC').match(/[\p{L}\p{M}]+/gu);
  return matches ? matches.length : 0;
}

function compileList(filePath) {
  const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));

  const entries = {};
  const seen = new Map();
  let maxWords = 0;

  for (const entry of data.entries) {
    const normalized = entry.normalize('NFC');
    const key = casefoldKey(normalized);

    if (seen.has(key)) {
      throw new Error(
        `Duplicate key "${key}" in list ${data.id}: ` +
        `"${seen.get(key)}" vs "${entry}"`);
    }
    seen.set(key, entry);

    entries[key] = normalized;

    const wc = wordCount(normalized);
    if (wc > maxWords) {
      maxWords = wc;
    }
  }

  // Deterministic ordinal key order for stable diffs (matches C# StringComparer.Ordinal).
  const sortedEntries = {};
  for (const key of Object.keys(entries).sort()) {
    sortedEntries[key] = entries[key];
  }

  return {
    id: data.id,
    version: data.version,
    description: data.description,
    maxWords,
    entries: sortedEntries
  };
}

function main() {
  const files = fs.readdirSync(listsDir)
    .filter(f => f.endsWith('.json') && f !== 'schema.json' && f !== 'manifest.json')
    .sort();

  if (files.length === 0) {
    console.error(`No Tallman list JSON files found in ${listsDir}`);
    process.exit(1);
  }

  const lists = {};
  for (const file of files) {
    const compiled = compileList(path.join(listsDir, file));
    const id = compiled.id;
    delete compiled.id; // id is the map key; don't duplicate it inside the entry
    if (lists[id]) {
      throw new Error(`Duplicate list id "${id}" (from ${file})`);
    }
    lists[id] = compiled;
  }

  // Sort lists by id.
  const sortedLists = {};
  for (const id of Object.keys(lists).sort()) {
    sortedLists[id] = lists[id];
  }

  const artifact = {
    _comment: 'GENERATED by tools/compile-lists. Source: tallman-lists/*.json. Do not edit by hand.',
    casefold: 'casefold(NFC(text)); currently toLowerCase(NFC(text)), exact for the ASCII/Latin entries (see spec 3.2)',
    lists: sortedLists
  };

  fs.mkdirSync(outDir, { recursive: true });
  fs.writeFileSync(outFile, JSON.stringify(artifact, null, 2) + '\n', 'utf8');

  const summary = Object.entries(sortedLists)
    .map(([id, l]) => `${id} (${Object.keys(l.entries).length} entries, maxWords=${l.maxWords})`)
    .join(', ');
  console.log(`Compiled ${files.length} lists -> ${path.relative(rootDir, outFile)}`);
  console.log(`  ${summary}`);
}

main();
