#!/usr/bin/env node
'use strict';
// Reads tallman-lists/compiled/lists.compiled.json and emits
// src/embedded-lists.ts — a native TypeScript object containing all lists.
// Run with: node tools/embed-lists.js
// Re-run whenever the compiled artifact changes.

const fs = require('fs');
const path = require('path');

const repoRoot = path.resolve(__dirname, '../../..');
const artifactPath = path.join(repoRoot, 'tallman-lists', 'compiled', 'lists.compiled.json');
const outputPath = path.join(repoRoot, 'languages', 'js', 'src', 'embedded-lists.ts');

const artifact = JSON.parse(fs.readFileSync(artifactPath, 'utf8'));
const lists = artifact.lists;
const listIds = Object.keys(lists).sort();

function escapeString(s) {
  return s.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}

const lines = [
  '// GENERATED by languages/js/tools/embed-lists.js',
  '// Source: tallman-lists/compiled/lists.compiled.json',
  '// DO NOT EDIT',
  '',
  'export interface ListData {',
  '  readonly version: string;',
  '  readonly description: string;',
  '  readonly maxWords: number;',
  '  readonly entries: Readonly<Record<string, string>>;',
  '}',
  '',
  'export const EMBEDDED_LISTS: Readonly<Record<string, ListData>> = {',
];

for (const id of listIds) {
  const list = lists[id];
  const entryKeys = Object.keys(list.entries).sort();

  lines.push(`  ${id}: {`);
  lines.push(`    version: '${escapeString(list.version)}',`);
  lines.push(`    description: '${escapeString(list.description)}',`);
  lines.push(`    maxWords: ${list.maxWords},`);
  lines.push(`    entries: {`);

  for (const key of entryKeys) {
    const value = list.entries[key];
    lines.push(`      '${escapeString(key)}': '${escapeString(value)}',`);
  }

  lines.push(`    },`);
  lines.push(`  },`);
}

lines.push('};');
lines.push('');

const content = lines.join('\n');
fs.writeFileSync(outputPath, content, 'utf8');
console.log(`Wrote ${outputPath}`);
