//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToTallman.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ToTallman.Properties.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aCLin
        ///actoNEL
        ///actoS
        ///aKAMin
        ///alDACTONE
        ///alDOMET
        ///ALKeran
        ///alODORM
        ///amARYl
        ///amiNOPHYLLine
        ///amiODAROne
        ///amiTRIPTYLine
        ///amLODIPine
        ///amOXil
        ///aPomine
        ///arABLOC
        ///arATAC
        ///ARIPiprazole
        ///arOPAX
        ///aTRopt
        ///avaSTIN
        ///avaXIM
        ///aVomine
        ///azATHIOPRINE
        ///aziTHROMYCIN
        ///aZopt
        ///bisACODYl
        ///bisOPROLOl
        ///buDESONide
        ///buMETANide
        ///caLTRate
        ///caPTOPRil
        ///caRAFate
        ///CARBAMazepine
        ///carbiMAZOLe
        ///cARBOplatin
        ///CARpine
        ///caRVEDILOl
        ///cefaLEXin
        ///cefALOTIN
        ///cefaZOLin
        ///cefEPIME
        ///cefOTAXIME
        ///cefOXITIN
        ///ceftAROLine
        ///cefTAZIDIME
        ///cefTRIAXONE
        ///celAPRAM
        ///c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AU_2017 {
            get {
                return ResourceManager.GetString("AU_2017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to acetaZOLAMIDE
        ///acetoHEXAMIDE
        ///buPROPion
        ///busPIRone
        ///chlorproMAZINE
        ///chlorproPAMIDE
        ///clomiPHENE
        ///clomiPRAMINE
        ///cycloSERINE
        ///cycloSPORINE
        ///DAUNOrubicin
        ///dimenhyDRINATE
        ///diphenhydrAMINE
        ///DOBUTamine
        ///DOPamine
        ///DOXOrubicin
        ///glipiZIDE
        ///glyBURIDE
        ///hydrALAZINE
        ///HYDROmorphone
        ///hydrOXYzine
        ///medroxyPROGESTERone
        ///methylPREDNISolone
        ///methylTESTOSTERone
        ///mitoXANTRONE
        ///niCARdipine
        ///NIFEdipine
        ///prednisoLONE
        ///predniSONE
        ///risperiDONE
        ///rOPINIRole
        ///sulfADIAZINE
        ///sulfiSOXAZOLE
        ///TOLAZamide
        ///TOLBUTamide
        ///vinBLAStine
        ///vinCRIStine        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FDA_2016 {
            get {
                return ResourceManager.GetString("FDA_2016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALPRAZolam
        ///aMILoride
        ///amLODIPine
        ///ARIPiprazole
        ///AVINza
        ///azaCITIDine
        ///azaTHIOprine
        ///carBAMazepine
        ///CARBOplatin
        ///ceFAZolin
        ///cefoTEtan
        ///cefOXitin
        ///cefTAZidime
        ///cefTRIAXone
        ///CeleBREX
        ///CeleXA
        ///chlordiazePOXIDE
        ///chlorproMAZINE
        ///CISplatin
        ///cloBAZam
        ///clonazePAM
        ///cloNIDine
        ///cloZAPine
        ///DACTINomycin
        ///DAPTOmycin
        ///DEPO-Medrol
        ///diazePAM
        ///dilTIAZem
        ///DOCEtaxel
        ///DOXOrubicin
        ///DULoxetine
        ///ePHEDrine
        ///EPINEPHrine
        ///epiRUBicin
        ///eriBULin
        ///fentaNYL
        ///flavoxATE
        ///FLUoxetine
        ///fluPHENAZine
        ///fluvoxaMINE
        ///guaiFENesin
        ///guanFACINE
        ///HumaLOG [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ISMP_2016 {
            get {
                return ResourceManager.GetString("ISMP_2016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALKeran
        ///aLLOPURINol
        ///amINOPHYLLIne
        ///amIODAROne
        ///amiSULPIRIDe
        ///amITRIPTYLIne
        ///amLODIPIne
        ///aPomine
        ///arATAC
        ///arOPAX
        ///aTENOLol
        ///aTRopt
        ///avaSTIN
        ///avaXIM
        ///aVomine
        ///azATHIOPRINE
        ///azITHROMYCIN
        ///aZopt
        ///BENZATHINE benzylpenicillin
        ///benzylpenicillin
        ///bisACODYl
        ///bisOPROLOl
        ///buDESONide
        ///buMETANide
        ///caLTRate
        ///caPTOPRIl
        ///caRAFate
        ///CARBAMazepine
        ///carbIMAZOLe
        ///cARBOplatin
        ///caRVEDILOl
        ///cefaLEXin
        ///cefaZOLin
        ///cefEPIME
        ///cefOTAXIME
        ///cefOXITIN
        ///cefTAZIDIME
        ///cefTRIAXONE
        ///cefUROXIME
        ///celAPRAM
        ///celEBREX
        ///cephaLEXin
        ///cephaZOLin
        ///CET [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NZ_2013 {
            get {
                return ResourceManager.GetString("NZ_2013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to actoNEL
        ///actoS
        ///aKAMin
        ///aCLin
        ///alDOMET
        ///alDACTONE
        ///alODORM
        ///amARYl
        ///amOXil
        ///amiODAROne
        ///amLODIPine
        ///amiTRIPTYLine
        ///amiNOPHYLLine
        ///aPomine
        ///aVomine
        ///arATAC
        ///arOPAX
        ///arABLOC
        ///ARIPiprazole
        ///RABEprazole
        ///aTRopt
        ///aZopt
        ///azATHIOPRINE
        ///aziTHROMYCIN
        ///ERYthromycin
        ///bisOPROLOl
        ///bisACODYl
        ///buMETANide
        ///buDESONide
        ///caRAFate
        ///caLTRate
        ///CARBAMazepine
        ///OXCARBazepine
        ///carbiMAZOLe
        ///caRVEDILOl
        ///caPTOPRil
        ///celAPRAM
        ///celEBREX
        ///ciprAMIL
        ///ciprOXIN
        ///cLARITHROMYcin
        ///ciPROFLOXAcin
        ///cLOMIPRAMine
        ///cLOMIPHEne
        ///cHLORPROMAZine
        ///coUMADIN        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Tallmen {
            get {
                return ResourceManager.GetString("Tallmen", resourceCulture);
            }
        }
    }
}
