# generate-embedded.ps1
#
# Thin C# emitter for the embedded Tall Man lists.
#
# All list semantics (NFC normalization, casefold match keys, per-list
# multi-word lookahead caps) are precomputed by the shared, language-agnostic
# compiler (tools/compile-lists) into tallman-lists/compiled/lists.compiled.json.
# This script ONLY serializes that artifact into C# - no normalization, no key
# derivation - so the C# embedding stays byte-identical to every other language.
#
# PowerShell 5.1 compatible; ASCII only.

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

# Paths
$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path          # languages/csharp/tools
$csharpDir = Split-Path -Parent $scriptDir                            # languages/csharp
$projectRoot = Split-Path -Parent (Split-Path -Parent $csharpDir)     # repo root
# Build paths with [IO.Path]::Combine so the correct separator is used on every
# OS (PowerShell 5.1 on Windows, pwsh on Linux/macOS in CI). Hardcoded backslashes
# would be treated as literal filename characters under pwsh on Linux.
$artifactFile = [System.IO.Path]::Combine($projectRoot, "tallman-lists", "compiled", "lists.compiled.json")
$outputFile = [System.IO.Path]::Combine($csharpDir, "src", "ToTallman", "EmbeddedTallmanLists.g.cs")

if (-not (Test-Path $artifactFile)) {
    Write-Error "Compiled list artifact not found: $artifactFile`nRun 'node tools/compile-lists/compile-lists.js' first."
    exit 1
}

Write-Host "Generating embedded Tallman lists from compiled artifact..." -ForegroundColor Cyan
Write-Host "  Artifact: $artifactFile"
Write-Host "  Output:   $outputFile"

$artifact = Get-Content $artifactFile -Raw -Encoding UTF8 | ConvertFrom-Json

# List ids, ordinal-sorted (matches C# StringComparer.Ordinal).
$listIds = @($artifact.lists.PSObject.Properties.Name)
[Array]::Sort($listIds, [System.StringComparer]::Ordinal)

function ConvertTo-CSharpLiteral([string]$value) {
    return $value.Replace("\", "\\").Replace('"', '\"')
}

$sb = New-Object System.Text.StringBuilder

[void]$sb.AppendLine("// <auto-generated />")
[void]$sb.AppendLine("// Generated by: languages/csharp/tools/generate-embedded.ps1")
[void]$sb.AppendLine("// Source: tallman-lists/compiled/lists.compiled.json")
[void]$sb.AppendLine("// DO NOT EDIT")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("using System;")
[void]$sb.AppendLine("using System.Collections.Generic;")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("namespace ToTallman")
[void]$sb.AppendLine("{")
[void]$sb.AppendLine("    internal static class EmbeddedTallmanLists")
[void]$sb.AppendLine("    {")
[void]$sb.AppendLine("        public static readonly IReadOnlyDictionary<string, IReadOnlyDictionary<string, string>> AllLists =")
[void]$sb.AppendLine("            new Dictionary<string, IReadOnlyDictionary<string, string>>(StringComparer.Ordinal)")
[void]$sb.AppendLine("            {")

foreach ($listId in $listIds) {
    $list = $artifact.lists.PSObject.Properties[$listId].Value
    $entriesObj = $list.entries

    [void]$sb.AppendLine("                [""$listId""] = new Dictionary<string, string>(StringComparer.Ordinal)")
    [void]$sb.AppendLine("                {")

    $keys = @($entriesObj.PSObject.Properties.Name)
    [Array]::Sort($keys, [System.StringComparer]::Ordinal)
    foreach ($key in $keys) {
        $value = $entriesObj.PSObject.Properties[$key].Value
        $escapedKey = ConvertTo-CSharpLiteral $key
        $escapedValue = ConvertTo-CSharpLiteral $value
        [void]$sb.AppendLine("                    [""$escapedKey""] = ""$escapedValue"",")
    }

    [void]$sb.AppendLine("                },")
}

[void]$sb.AppendLine("            };")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("        public static readonly IReadOnlySet<string> AvailableListIds =")
[void]$sb.AppendLine("            new HashSet<string>(StringComparer.Ordinal)")
[void]$sb.AppendLine("            {")

foreach ($listId in $listIds) {
    [void]$sb.AppendLine("                ""$listId"",")
}

[void]$sb.AppendLine("            };")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("        public static readonly IReadOnlyDictionary<string, int> MaxWordCounts =")
[void]$sb.AppendLine("            new Dictionary<string, int>(StringComparer.Ordinal)")
[void]$sb.AppendLine("            {")

foreach ($listId in $listIds) {
    $list = $artifact.lists.PSObject.Properties[$listId].Value
    $mw = $list.maxWords
    [void]$sb.AppendLine("                [""$listId""] = $mw,")
}

[void]$sb.AppendLine("            };")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("        public static readonly IReadOnlyDictionary<string, string> Versions =")
[void]$sb.AppendLine("            new Dictionary<string, string>(StringComparer.Ordinal)")
[void]$sb.AppendLine("            {")

foreach ($listId in $listIds) {
    $list = $artifact.lists.PSObject.Properties[$listId].Value
    $ver = ConvertTo-CSharpLiteral $list.version
    [void]$sb.AppendLine("                [""$listId""] = ""$ver"",")
}

[void]$sb.AppendLine("            };")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("        public static IReadOnlyDictionary<string, string> GetList(string listId)")
[void]$sb.AppendLine("        {")
[void]$sb.AppendLine("            if (listId != null && AllLists.TryGetValue(listId, out var list))")
[void]$sb.AppendLine("            {")
[void]$sb.AppendLine("                return list;")
[void]$sb.AppendLine("            }")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("            throw new TallmanException(""Unknown Tallman list ID: '"" + listId + ""'. Available lists: "" + string.Join("", "", AvailableListIds) + ""."");")
[void]$sb.AppendLine("        }")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("        public static int GetMaxWordCount(string listId)")
[void]$sb.AppendLine("        {")
[void]$sb.AppendLine("            if (listId != null && MaxWordCounts.TryGetValue(listId, out var count))")
[void]$sb.AppendLine("            {")
[void]$sb.AppendLine("                return count;")
[void]$sb.AppendLine("            }")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("            return 1;")
[void]$sb.AppendLine("        }")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("        public static string GetVersion(string listId)")
[void]$sb.AppendLine("        {")
[void]$sb.AppendLine("            if (listId != null && Versions.TryGetValue(listId, out var version))")
[void]$sb.AppendLine("            {")
[void]$sb.AppendLine("                return version;")
[void]$sb.AppendLine("            }")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("            throw new TallmanException(""Unknown Tallman list ID: '"" + listId + ""'. Available lists: "" + string.Join("", "", AvailableListIds) + ""."");")
[void]$sb.AppendLine("        }")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("        public static bool HasList(string listId)")
[void]$sb.AppendLine("        {")
[void]$sb.AppendLine("            return AllLists.ContainsKey(listId);")
[void]$sb.AppendLine("        }")
[void]$sb.AppendLine("    }")
[void]$sb.AppendLine("}")

$sb.ToString() | Out-File -FilePath $outputFile -Encoding UTF8

Write-Host "Success! Generated $outputFile" -ForegroundColor Green
Write-Host "  Lists: $($listIds.Count)"

exit 0
