#!/usr/bin/env node
/**
 * Thin Java emitter for embedded Tall Man lists.
 *
 * All list semantics (NFC normalization, casefold match keys, per-list multi-word lookahead
 * caps) are precomputed by the shared, language-agnostic compiler (tools/compile-lists) into
 * tallman-lists/compiled/lists.compiled.json. This script ONLY serializes that artifact as
 * Java -- no normalization, no key derivation -- so the Java embedding stays byte-identical to
 * every other language.
 *
 * Usage (from repo root):
 *   node languages/java/tools/embed-lists.js
 */

'use strict';

const fs = require('fs');
const path = require('path');

const repoRoot = path.resolve(__dirname, '../../..');
const artifactPath = path.join(repoRoot, 'tallman-lists', 'compiled', 'lists.compiled.json');
const outputPath = path.join(
    repoRoot,
    'languages',
    'java',
    'src',
    'main',
    'java',
    'com',
    'totallman',
    'EmbeddedTallmanLists.java'
);

if (!fs.existsSync(artifactPath)) {
    console.error(
        `Compiled list artifact not found: ${artifactPath}\n` +
        "Run 'node tools/compile-lists/compile-lists.js' first."
    );
    process.exit(1);
}

console.log('Generating embedded Tallman lists from compiled artifact...');
console.log(`  Artifact: ${artifactPath}`);
console.log(`  Output:   ${outputPath}`);

const artifact = JSON.parse(fs.readFileSync(artifactPath, 'utf8'));
const lists = artifact.lists;

// Ordinal sort matches compile-lists.js, embed_lists.py, and generate-embedded.ps1 for stable diffs.
const listIds = Object.keys(lists).sort();

function javaStr(value) {
    return '"' + value.replace(/\\/g, '\\\\').replace(/"/g, '\\"') + '"';
}

const lines = [];

lines.push('package com.totallman;');
lines.push('');
lines.push('// GENERATED by languages/java/tools/embed-lists.js');
lines.push('// Source: tallman-lists/compiled/lists.compiled.json');
lines.push('// DO NOT EDIT');
lines.push('');
lines.push('import java.util.Collections;');
lines.push('import java.util.HashMap;');
lines.push('import java.util.HashSet;');
lines.push('import java.util.Map;');
lines.push('import java.util.Set;');
lines.push('');
lines.push('/** Embedded Tall Man lists, generated at build time. No runtime I/O. */');
lines.push('final class EmbeddedTallmanLists {');
lines.push('');
lines.push('    private EmbeddedTallmanLists() {}');
lines.push('');

// ALL_LISTS static initializer
lines.push('    static final Map<String, Map<String, String>> ALL_LISTS;');
lines.push('');
lines.push('    static {');
lines.push(`        Map<String, Map<String, String>> allLists = new HashMap<>(${listIds.length});`);

for (const listId of listIds) {
    const lst = lists[listId];
    const entries = lst.entries;
    const sortedKeys = Object.keys(entries).sort();
    lines.push(`        Map<String, String> ${listId.toLowerCase()}Map = new HashMap<>(${sortedKeys.length});`);
    for (const key of sortedKeys) {
        lines.push(`        ${listId.toLowerCase()}Map.put(${javaStr(key)}, ${javaStr(entries[key])});`);
    }
    lines.push(`        allLists.put(${javaStr(listId)}, Collections.unmodifiableMap(${listId.toLowerCase()}Map));`);
}

lines.push(`        ALL_LISTS = Collections.unmodifiableMap(allLists);`);
lines.push('    }');
lines.push('');

// MAX_WORD_COUNTS
lines.push('    static final Map<String, Integer> MAX_WORD_COUNTS;');
lines.push('');
lines.push('    static {');
lines.push(`        Map<String, Integer> maxWords = new HashMap<>(${listIds.length});`);
for (const listId of listIds) {
    lines.push(`        maxWords.put(${javaStr(listId)}, ${lists[listId].maxWords});`);
}
lines.push('        MAX_WORD_COUNTS = Collections.unmodifiableMap(maxWords);');
lines.push('    }');
lines.push('');

// VERSIONS
lines.push('    static final Map<String, String> VERSIONS;');
lines.push('');
lines.push('    static {');
lines.push(`        Map<String, String> versions = new HashMap<>(${listIds.length});`);
for (const listId of listIds) {
    lines.push(`        versions.put(${javaStr(listId)}, ${javaStr(lists[listId].version)});`);
}
lines.push('        VERSIONS = Collections.unmodifiableMap(versions);');
lines.push('    }');
lines.push('');

// AVAILABLE_LIST_IDS
lines.push('    static final Set<String> AVAILABLE_LIST_IDS;');
lines.push('');
lines.push('    static {');
lines.push(`        Set<String> ids = new HashSet<>(${listIds.length});`);
for (const listId of listIds) {
    lines.push(`        ids.add(${javaStr(listId)});`);
}
lines.push('        AVAILABLE_LIST_IDS = Collections.unmodifiableSet(ids);');
lines.push('    }');
lines.push('');

// Accessor methods
lines.push('    /** Return the casefold-to-canonical map for listId. */');
lines.push('    static Map<String, String> getList(String listId) {');
lines.push('        Map<String, String> list = ALL_LISTS.get(listId);');
lines.push('        if (list != null) {');
lines.push('            return list;');
lines.push('        }');
lines.push('        String available = String.join(", ", AVAILABLE_LIST_IDS.stream().sorted().toArray(String[]::new));');
lines.push('        throw new TallmanException("Unknown Tallman list ID: \'" + listId + "\'. Available lists: " + available + ".");');
lines.push('    }');
lines.push('');
lines.push('    /** Return the maxWords lookahead cap for listId (default 1). */');
lines.push('    static int getMaxWordCount(String listId) {');
lines.push('        return MAX_WORD_COUNTS.getOrDefault(listId, 1);');
lines.push('    }');
lines.push('');
lines.push('    /** Return the version string for listId. */');
lines.push('    static String getVersion(String listId) {');
lines.push('        String version = VERSIONS.get(listId);');
lines.push('        if (version != null) {');
lines.push('            return version;');
lines.push('        }');
lines.push('        String available = String.join(", ", AVAILABLE_LIST_IDS.stream().sorted().toArray(String[]::new));');
lines.push('        throw new TallmanException("Unknown Tallman list ID: \'" + listId + "\'. Available lists: " + available + ".");');
lines.push('    }');
lines.push('');
lines.push('    /** Return an unmodifiable view of all available list IDs. */');
lines.push('    static Set<String> availableListIds() {');
lines.push('        return AVAILABLE_LIST_IDS;');
lines.push('    }');
lines.push('');
lines.push('}');
lines.push('');

fs.writeFileSync(outputPath, lines.join('\n'), 'utf8');
console.log(`Success! Generated ${outputPath}`);
console.log(`  Lists: ${listIds.length}`);
