#!/usr/bin/env python3
"""Thin Python emitter for embedded Tall Man lists.

All list semantics (NFC normalization, casefold match keys, per-list
multi-word lookahead caps) are precomputed by the shared, language-agnostic
compiler (tools/compile-lists) into tallman-lists/compiled/lists.compiled.json.
This script ONLY serializes that artifact as Python -- no normalization, no
key derivation -- so the Python embedding stays byte-identical to every other
language.

Usage (from repo root):
    python languages/python/tools/embed_lists.py
"""

from __future__ import annotations

import json
import pathlib
import sys

REPO_ROOT = pathlib.Path(__file__).resolve().parents[3]
ARTIFACT = REPO_ROOT / "tallman-lists" / "compiled" / "lists.compiled.json"
OUTPUT = REPO_ROOT / "languages" / "python" / "src" / "totallman" / "_embedded_lists.py"


def _py_str(value: str) -> str:
    """Return a Python string literal for value (double-quoted, escaped)."""
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main() -> int:
    if not ARTIFACT.exists():
        print(
            f"Compiled list artifact not found: {ARTIFACT}\n"
            "Run 'node tools/compile-lists/compile-lists.js' first.",
            file=sys.stderr,
        )
        return 1

    print("Generating embedded Tallman lists from compiled artifact...")
    print(f"  Artifact: {ARTIFACT}")
    print(f"  Output:   {OUTPUT}")

    with ARTIFACT.open(encoding="utf-8") as fh:
        artifact = json.load(fh)

    lists: dict = artifact["lists"]
    # Ordinal sort matches compile-lists.js and generate-embedded.ps1 for stable diffs.
    list_ids = sorted(lists.keys())

    lines: list[str] = []
    lines.append("# GENERATED by languages/python/tools/embed_lists.py")
    lines.append("# Source: tallman-lists/compiled/lists.compiled.json")
    lines.append("# DO NOT EDIT")
    lines.append("")
    lines.append("from __future__ import annotations")
    lines.append("")
    lines.append("from totallman.exceptions import TallmanError")
    lines.append("")

    # ALL_LISTS: dict[str, dict[str, str]]  casefold_key -> canonical_form
    lines.append("ALL_LISTS: dict[str, dict[str, str]] = {")
    for list_id in list_ids:
        lst = lists[list_id]
        lines.append(f"    {_py_str(list_id)}: {{")
        for key in sorted(lst["entries"].keys()):
            value = lst["entries"][key]
            lines.append(f"        {_py_str(key)}: {_py_str(value)},")
        lines.append("    },")
    lines.append("}")
    lines.append("")

    # MAX_WORD_COUNTS
    lines.append("MAX_WORD_COUNTS: dict[str, int] = {")
    for list_id in list_ids:
        lines.append(f"    {_py_str(list_id)}: {lists[list_id]['maxWords']},")
    lines.append("}")
    lines.append("")

    # VERSIONS
    lines.append("VERSIONS: dict[str, str] = {")
    for list_id in list_ids:
        lines.append(f"    {_py_str(list_id)}: {_py_str(lists[list_id]['version'])},")
    lines.append("}")
    lines.append("")

    # AVAILABLE_LIST_IDS
    lines.append("AVAILABLE_LIST_IDS: frozenset[str] = frozenset({")
    for list_id in list_ids:
        lines.append(f"    {_py_str(list_id)},")
    lines.append("})")
    lines.append("")

    # Accessor functions (mirrors EmbeddedTallmanLists.g.cs)
    lines.append("")
    lines.append("def get_list(list_id: str) -> dict[str, str]:")
    lines.append('    """Return the casefold->canonical dict for list_id."""')
    lines.append("    if list_id in ALL_LISTS:")
    lines.append("        return ALL_LISTS[list_id]")
    lines.append('    available = ", ".join(sorted(AVAILABLE_LIST_IDS))')
    lines.append(
        "    raise TallmanError("
        "f\"Unknown Tallman list ID: '{list_id}'. Available lists: {available}.\")"
    )
    lines.append("")
    lines.append("")
    lines.append("def get_max_word_count(list_id: str) -> int:")
    lines.append('    """Return the maxWords lookahead cap for list_id (default 1)."""')
    lines.append("    return MAX_WORD_COUNTS.get(list_id, 1)")
    lines.append("")
    lines.append("")
    lines.append("def get_version(list_id: str) -> str:")
    lines.append('    """Return the version string for list_id."""')
    lines.append("    if list_id in VERSIONS:")
    lines.append("        return VERSIONS[list_id]")
    lines.append('    available = ", ".join(sorted(AVAILABLE_LIST_IDS))')
    lines.append(
        "    raise TallmanError("
        "f\"Unknown Tallman list ID: '{list_id}'. Available lists: {available}.\")"
    )
    lines.append("")
    lines.append("")
    lines.append("def has_list(list_id: str) -> bool:")
    lines.append('    """Return True if list_id is a known list."""')
    lines.append("    return list_id in ALL_LISTS")
    lines.append("")

    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Success! Generated {OUTPUT}")
    print(f"  Lists: {len(list_ids)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
